### ISSUE TITLE
Calling method from Native Not Working. Getting error - MissingPluginException No implementation found on channel

### ISSUE THREAD

**Issue by jaimin15** [Dev-hwang/flutter_foreground_task#107]
I'm making project on IOT so I'm trying to call start BLE scan functionality from Native android from onStart Method at that time I'm getting error of MissingPluginException No implementation found on channel. So how can i use Native methods. If it is possible in foreground and background share me demo or example.

**Comment by Dev-hwang** [comment]
It may be difficult to scan ble devices in the background using this plugin. See this [repository](https://github.com/Dev-hwang/flutter_ble_identification). Contains logic to scan for ble devices in the background.

**Comment by GaelleJoubert** [comment]
I have the same issue. 
I was also using flutter_reactive_ble and flutter_foreground task, and it was working well.
But since I updated the repo, it is working in debug but not in release anymore. 
It throws the same error : MissingPlugging exception.

@akospwc is it still working in release with the last version of the library for you ?

**Comment by Dev-hwang** [comment]
move issue #149
