### ISSUE TITLE
Foreground service stops after few hours

### ISSUE THREAD

**Issue by darshansatra1** [Dev-hwang/flutter_foreground_task#13]
Currently, I'm trying to implement a step counter which is calculated by foreground service having pedometer stream. I have observed that after few hours the foreground service stops, although the notification is still showing. Is there an alternative approach for solving this issue?

**Comment by Dev-hwang** [comment]
The above problem seems to be related to the Android doze mode or not handling the exception that occurs inside the initDispatcher function.

Try the following:

1. Not recommended to use `cancelOnError` when subscribing to a stream. because, if an error occurs during stream operation, the foreground service does not terminate, only the stream. Change it to false or remove it.
![image](https://user-images.githubusercontent.com/47127353/128674823-aefe7282-01f7-454c-8fc9-700fcf91328b.png)

2. Handle the exception by wrapping the code inside the initDispatcher function with `try-catch`. Well written in the example above, but I don't know right now.

3. Starting with Android 6.0 (API level 23), Android uses power saving features to optimize the battery. If the app is in the background, certain features may not be available due to [doze restrictions](https://developer.android.com/training/monitoring-device-state/doze-standby#restrictions). In some cases, an exception is thrown when trying to use the resource. Refer to [this page](https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases) to turn off battery optimization.

**Comment by Dev-hwang** [comment]
Still having issues?

**Comment by darshansatra1** [comment]
The issue is still there, after some time the steps just stops counting. I tried an interval update of 1 hour and checked but after few hours, the service still stops.

**Comment by Dev-hwang** [comment]
The above problem did not occur when using the Geolocator plugin. I'll try with the pedometer plugin.

**Comment by Dev-hwang** [comment]
I've been using this plugin with the pedometer plugin for 3 days and haven't had any issues. Still works fine in the background.

I need more information to test.
1. Requires device os version and brand.
2. Information from executing `flutter doctor` command.
3. Please tell me specifically what you do when a step event occurs.
4. Please tell me specifically under what circumstances the foreground service stops.
-- `Build Mode`: Debug or Release?
-- `Task Interval`: 
-- `Task Location`: Foreground or Background?
-- `When`: few hours
-- `Task`: What does the app do when an error occurs? or are you just walking?

**Comment by darshansatra1** [comment]
flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.4-0.0.pre.1, on Microsoft Windows [Version 10.0.22000.160], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.59.1)
[√] Connected device (2 available)

• No issues found!
```

Build Mode: Issue occurs in both Debug and Release
Task Interval: 1 hour, although there is a pedometer stream running inside.
App Location: Background(When the app is terminated)
When: 3-4 hours
Task: Mostly I think when I'm not walking after few hours, this error occurs.
Device: Samsung M31

**Comment by Dev-hwang** [comment]
I will test it according to the environment. What do you do when a pedometer event occurs? (For example, data storage in DB, network communication, etc.)

**Comment by darshansatra1** [comment]
Yes, DB store, I used **Objext_Box** for storing steps in the DB.
