### ISSUE TITLE
[Ask] Multiple foreground services

### ISSUE THREAD

**Issue by feriyalsusanto** [Dev-hwang/flutter_foreground_task#138]
Can we have multiple foreground services using this library? I tried to start service multiple times but the notification only showing 1.
Thanks

**Comment by Dev-hwang** [comment]
No. Currently, only one foreground service can be started. In the future, i will be able to start multiple foreground services depending on the notification id settings.

**Comment by feriyalsusanto** [comment]
Great, thanks for the information!

**Comment by Simonovsky** [comment]
Just wanna say, I miss this feature as well. 
There are many reasons you might want to have multiple services on foreground.

It would be best to have the possibility to have multiple services on one notification so we prevent spamming users. I'm mentioning this because you mentioned in the previous answer multiple notification ids and if I remember correctly on android one notification id = one notification. 

Anyway, thank you for the plugin :)

**Comment by mdmohsin7** [comment]
+1

Currently in my app I have certain permission which user might deny. In case if they allow the permission, I want to start the foreground service for that specific functionality. If they don't allow, I want to start foreground service for other functionality

**Comment by Mistic92** [comment]
Hi, is there any update about this feature?
