### ISSUE TITLE
launchApp and wakeUpScreen do nothing on iOS?

### ISSUE THREAD

**Issue by explodus** [Dev-hwang/flutter_foreground_task#256]
I want to show my own Alarm Screen if the App got into the background. In Android it works fine. Screen wakes up, App get launched and my screen get shown. In iOS it does nothing. I have to unlock the screen by myself and switch to the App and then the App reacts and show my Screen.

**Comment by Dev-hwang** [comment]
The above features are not available on iOS. Additionally, the task cannot be performed in real time due to background limitations of the iOS platform. This will run in the background for only 30 seconds.

If you want to continue working even when the app is closed, try this [plugin](https://pub.dev/packages/flutter_background_service).

**Comment by Dev-hwang** [comment]
The above features are not available on iOS platform. Additionally, the task cannot be performed in real time due to background limitations on iOS platform. This will run in the background for only 30 seconds.

If you want to continue working even when the app is closed, try this [plugin](https://pub.dev/packages/flutter_background_service).

**Comment by explodus** [comment]
Yes, I have already found out the iOS restriction. I will solve it using notifications. Because working in the background is working very well at the moment, as I only check for a Bluetooth connection and iOS allows that.
