### ISSUE TITLE
in ios location service not workin while app in background, any workarounds?

### ISSUE THREAD

**Issue by Abdurahmon727** [Dev-hwang/flutter_foreground_task#272]
default location service in example folder not working in ios background

**Comment by Dev-hwang** [comment]
@Abdurahmon727 

On the iOS platform, background tasks only work for 15~30 seconds.

This is a limitation of the iOS platform.

In addition, this plugin has not implemented BGTaskScheduler, so the task will destroy when the app exits.

https://github.com/Dev-hwang/flutter_foreground_task?tab=readme-ov-file#baby_chick-ios

**Comment by Dev-hwang** [comment]
And I'm planning to add an option using BGTaskScheduler so that the task can be scheduled even when the app is closed.

**Comment by Dev-hwang** [comment]
@Abdurahmon727 

On the iOS platform, background tasks only work for 15~30 seconds.

This is a limitation of the iOS platform.

Additionally, this plugin does not implement BGTaskScheduler, so tasks will be deleted when the app exits.

The [readme](https://github.com/Dev-hwang/flutter_foreground_task?tab=readme-ov-file#baby_chick-ios) explains the limitations of this plugin.

And I'm planning to add an option using BGTaskScheduler so that the task can be scheduled even when the app is closed.
