### ISSUE TITLE
Accessing native plugin from TaskHandler

### ISSUE THREAD

**Issue by insidewhy** [Dev-hwang/flutter_foreground_task#35]
Hi,

I want to access the Wi-Fi SSID, BSSID and RSSI from my TaskHandler so I can measure how the wifi strength varies over time. In the `onEvent` method of my `TaskHandler` I'm calling `WifiInfoAndroid.getWifiInfo` which is from the `wifi_info_android` plugin. The code for that is pretty simple, it can be found here: https://github.com/sol-x/wifi_info_android/blob/main/android/src/main/kotlin/co/solx/wifi_info_android/WifiInfoAndroidPlugin.kt

When trying to access the wifi info from the TaskHandler I always get a `null` value though. I'm not sure if there is a general issue with calling native code via a `MethodChannel` from a `TaskHandler` or if it's something specific to do with activity aware plugins.

Maybe I should be accessing the wifi info from `receivePort.listen` and only using the `sendPort` in the `TaskHandler` to indicate that the main thread should be accessing the wifi info?

**Comment by Dev-hwang** [comment]
When your app is in the background, it doesn't have an `Activity` object. The plugin you introduced is implemented so that null is always returned if there is no `Activity` object. - [Line45](https://github.com/sol-x/wifi_info_android/blob/aaa8d9ee472cd2060e4604df94d38fa43ca8f7b2/android/src/main/kotlin/co/solx/wifi_info_android/WifiInfoAndroidPlugin.kt#L45)

Try implementing it using `flutterPluginBinding.applicationContext` in `onAttachedToEngine` function instead of `binding.activity`.

**Comment by insidewhy** [comment]
@Dev-hwang Thanks for the quick response, you really helped :)
