### ISSUE TITLE
Shared_preferences reset when used in combo

### ISSUE THREAD

**Issue by EnricoTirri** [Dev-hwang/flutter_foreground_task#56]
If i use this dependency with also the shared_preferences dependency, it always reset the shared_preferences configuration, it doesn't give any error, it just reset it

**Comment by rahulmawana** [comment]
are you clearing all the data like following on destroy on service or anyother place?
Future<void> onDestroy(DateTime timestamp) async {
    // You can use the clearAllData function to clear all the stored data.
    await FlutterForegroundTask.clearAllData();
  }
If Yes then I think it will clear all the shared preference data

**Comment by irjayjay** [comment]
@Dev-hwang, any ideas what this could be?
When I run a foreground service, it resets the unrelated Shared Preferences that my app uses.

**Comment by irjayjay** [comment]
So far my investigation shows that the `FlutterForegroundTask.setTaskHandler()` is to blame. Shared preferences only reset if I run that. 
Will dig further into the code to see where it leads.

**Comment by irjayjay** [comment]
False positive on the previous cause.
Traced it down to `ForegroundService.kt` line 248 `stopSelf()`

My Kotlin isn't that great anymore but I have to get my feature out today.

**Comment by irjayjay** [comment]
Well, this is awkward, seems the issue isn't with the library itself, but with its demo, which I copied to implement the foreground task. 🤦 

Well... it kinda is with the library too, since the clearAllData() method CLEARS ALL DATA.

If you used the demo code too:
In the TaskHandler, in the `onDestroy` method remove the line:
```await FlutterForegroundTask.clearAllData();```

Also never run `FlutterForegroundTask.clearAllData();` anywhere else.
