### ISSUE TITLE
FATAL EXCEPTION (Android 12)

### ISSUE THREAD

**Issue by UserSense** [Dev-hwang/flutter_foreground_task#61]
The following error occurs:

```
E/AndroidRuntime(32695): FATAL EXCEPTION: main
E/AndroidRuntime(32695): java.lang.RuntimeException: Unable to start receiver com.pravera.flutter_foreground_task.service.RestartReceiver: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service io.usersense.app/com.pravera.flutter_foreground_task.service.ForegroundService
```

This happens in the following situation:

1. On detach of the app, with Foreground task running
2. My software detects the detach action and tries to stop the Foreground task by calling await FlutterForegroundTask.stopService()
3. A second later the above error appears.

Is seems that the FlutterForegroundTask.stopService() is not registered correct on an detach event.

During the close action (state detached) the following interestings message appears:

`The foreground service was terminated due to an unexpected problem. Set a restart alarm.`

Restart alarm should not have been set.

My guess is that the `RestartReceiver` function should also check whether it is allowed to start, or at least catch the Exception, or more general one should check whether the service can be started at all.

This seems to be related to the additional restrictions in Android 12.

I do not need the foreground service in case the app is closed/detached. I only need it for media projection during app usage.

**Comment by grzegorz-kozlowski** [comment]
I'd like to add another scenario to fatal exception which @UserSense mentioned. App also crashes when you tap on notification (with intention to bring app foreground).

Steps:

1. Start foreground service
2. Call FlutterForegroundTask.minimizeApp();
3. Tap on foreground service notification



Log:
`D/AndroidRuntime(11717): Shutting down VM
E/AndroidRuntime(11717): FATAL EXCEPTION: main
E/AndroidRuntime(11717): Process: com.iteo.bmpro.prosmart, PID: 11717
E/AndroidRuntime(11717): java.lang.RuntimeException: Unable to start service com.pravera.flutter_foreground_task.service.ForegroundService@eb26862 with Intent { cmp=com.iteo.bmpro.prosmart/com.pravera.flutter_foreground_task.service.ForegroundService }: java.lang.IllegalArgumentException
E/AndroidRuntime(11717): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5112)
E/AndroidRuntime(11717): 	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
E/AndroidRuntime(11717): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
E/AndroidRuntime(11717): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11717): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(11717): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(11717): 	at android.app.ActivityThread.main(ActivityThread.java:8641)
E/AndroidRuntime(11717): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11717): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/AndroidRuntime(11717): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
E/AndroidRuntime(11717): Caused by: java.lang.IllegalArgumentException
E/AndroidRuntime(11717): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2441)
E/AndroidRuntime(11717): 	at android.os.Parcel.createException(Parcel.java:2421)
E/AndroidRuntime(11717): 	at android.os.Parcel.readException(Parcel.java:2404)
E/AndroidRuntime(11717): 	at android.os.Parcel.readException(Parcel.java:2346)
E/AndroidRuntime(11717): 	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:4790)
E/AndroidRuntime(11717): 	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1042)
E/AndroidRuntime(11717): 	at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:947)
E/AndroidRuntime(11717): 	at com.pravera.flutter_foreground_task.service.ForegroundService.startForegroundService(ForegroundService.kt:202)
E/AndroidRuntime(11717): 	at com.pravera.flutter_foreground_task.service.ForegroundService.onStartCommand(ForegroundService.kt:98)
E/AndroidRuntime(11717): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5094)
E/AndroidRuntime(11717): 	... 9 more
E/AndroidRuntime(11717): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(11717): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:44)
E/AndroidRuntime(11717): 	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:1011)
E/AndroidRuntime(11717): 	at com.android.server.notification.NotificationManagerService$14.createNotificationChannelsImpl(NotificationManagerService.java:4469)
E/AndroidRuntime(11717): 	at com.android.server.notification.NotificationManagerService$14.createNotificationChannels(NotificationManagerService.java:4500)
E/AndroidRuntime(11717): 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1858)
E/AndroidRuntime(11717): 
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"744","method":"resume","params":{"isolateId":"isolates/253483496401195"}}
Failed to send request: {"jsonrpc":"2.0","id":"745","method":"getStack","params":{"isolateId":"isolates/253483496401195"}}`

**Comment by Dev-hwang** [comment]
This issue seems to occur on the Android 12 platform. Check [this page](https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions) if foreground services are allowed to run in the background.

Here's what we can try:
```text
The user turns off battery optimizations for your app. You can help users find this option by sending them to your app's App info page in system settings. To do so, invoke an intent that contains the [ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS](https://developer.android.com/reference/android/provider/Settings#ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS) intent action.
```

This plugin provides a function to turn off battery optimization. Turn off battery optimization by calling the `requestIgnoreBatteryOptimization()` function.

**Comment by Dev-hwang** [comment]
If you want to use the service only while using the app, set it up as follows.

1. Set the `isSticky` option to `false`.
```dart
  Future<void> _initForegroundTask() async {
    await FlutterForegroundTask.init(
      androidNotificationOptions: AndroidNotificationOptions(
        channelId: 'notification_channel_id',
        channelName: 'Foreground Notification',
        channelDescription:
            'This notification appears when the foreground service is running.',
        channelImportance: NotificationChannelImportance.LOW,
        priority: NotificationPriority.LOW,
        isSticky: false, // here
      ),
      iosNotificationOptions: const IOSNotificationOptions(
        showNotification: true,
        playSound: false,
      ),
      foregroundTaskOptions: const ForegroundTaskOptions(
        interval: 5000,
        autoRunOnBoot: true,
        allowWifiLock: true,
      ),
      printDevLog: true,
    );
  }
```

2. Set `stopWithTask` option to `true` in AndroidManifest.xml file.
```xml
<service
        android:name="com.pravera.flutter_foreground_task.service.ForegroundService"
        android:stopWithTask="true" />
```

**Comment by UserSense** [comment]
@Dev-hwang Still the error shouldn't be there. By adding the isSticky: false we just disable the restart mechanism.

The code  automatic restart trigger should check whether it is allowed/able to restart or not. Start conditions have changed since Android 12. 

So even if one requires the automatic restart additional checks are needed.

One could work around it with a bit of additional effort.

**Comment by Dev-hwang** [comment]
You can try the improved features before the plugin is released. Please tell me if there is something missing.

```yaml
dependencies:
  # flutter_foreground_task: ^3.7.2
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: master
```

**Comment by ShoaibKakal** [comment]
> I'd like to add another scenario to fatal exception which @UserSense mentioned. App also crashes when you tap on notification (with intention to bring app foreground).
> 
> Steps:
> 
> 1. Start foreground service
> 2. Call FlutterForegroundTask.minimizeApp();
> 3. Tap on foreground service notification
> 
> Log:
> 
> ```
> D/AndroidRuntime(11717): Shutting down VM
> E/AndroidRuntime(11717): FATAL EXCEPTION: main
> E/AndroidRuntime(11717): java.lang.RuntimeException: Unable to start service com.pravera.flutter_foreground_task.service.ForegroundService@eb26862 with Intent { cmp=com.example/com.pravera.flutter_foreground_task.service.ForegroundService }: java.lang.IllegalArgumentException
> E/AndroidRuntime(11717): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5112)
> E/AndroidRuntime(11717): 	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
> E/AndroidRuntime(11717): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
> E/AndroidRuntime(11717): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(11717): 	at android.os.Looper.loopOnce(Looper.java:226)
> E/AndroidRuntime(11717): 	at android.os.Looper.loop(Looper.java:313)
> E/AndroidRuntime(11717): 	at android.app.ActivityThread.main(ActivityThread.java:8641)
> E/AndroidRuntime(11717): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(11717): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
> E/AndroidRuntime(11717): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
> E/AndroidRuntime(11717): Caused by: java.lang.IllegalArgumentException
> E/AndroidRuntime(11717): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2441)
> E/AndroidRuntime(11717): 	at android.os.Parcel.createException(Parcel.java:2421)
> E/AndroidRuntime(11717): 	at android.os.Parcel.readException(Parcel.java:2404)
> E/AndroidRuntime(11717): 	at android.os.Parcel.readException(Parcel.java:2346)
> E/AndroidRuntime(11717): 	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:4790)
> E/AndroidRuntime(11717): 	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:1042)
> E/AndroidRuntime(11717): 	at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:947)
> E/AndroidRuntime(11717): 	at com.pravera.flutter_foreground_task.service.ForegroundService.startForegroundService(ForegroundService.kt:202)
> E/AndroidRuntime(11717): 	at com.pravera.flutter_foreground_task.service.ForegroundService.onStartCommand(ForegroundService.kt:98)
> E/AndroidRuntime(11717): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5094)
> E/AndroidRuntime(11717): 	... 9 more
> E/AndroidRuntime(11717): Caused by: android.os.RemoteException: Remote stack trace:
> E/AndroidRuntime(11717): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:44)
> E/AndroidRuntime(11717): 	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:1011)
> E/AndroidRuntime(11717): 	at com.android.server.notification.NotificationManagerService$14.createNotificationChannelsImpl(NotificationManagerService.java:4469)
> E/AndroidRuntime(11717): 	at com.android.server.notification.NotificationManagerService$14.createNotificationChannels(NotificationManagerService.java:4500)
> E/AndroidRuntime(11717): 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1858)
> E/AndroidRuntime(11717): 
> Lost connection to device.
> Failed to send request: {"jsonrpc":"2.0","id":"744","method":"resume","params":{"isolateId":"isolates/253483496401195"}}
> Failed to send request: {"jsonrpc":"2.0","id":"745","method":"getStack","params":{"isolateId":"isolates/253483496401195"}}
> ```

were you able to solve this error?
