### ISSUE TITLE
Add option to disable CPU wake lock

### ISSUE THREAD

**Issue by TheLastGimbus** [Dev-hwang/flutter_foreground_task#98]
Hi!
Thank you so much for keeping up the work with this plugin, it's so helpful!

I will have a service that will be running for long time (to keep connection with bluetooth peripheral) - I'm wondering if constant CPU lock won't drain the battery too much :grimacing: - could you add an option to **not** hold the cpu?

**Comment by h2210316651** [comment]
Believe it or not there are hundreds if not thousands of processes that prevent your cpu from sleeping. Mobile operating systems have a clear advantage at handling these since arm processors have efficiency cores and performance cores. Having an option to disable cpu wake lock is great but you would not a significant battery performance boost with that.

**Comment by TheLastGimbus** [comment]
Mmm, as far as i know, only apps with a running foreground service have option to do that. I know that there are thousands processes already running, but I belive (maybe stupidly) that Android can optimize stuff nicely if I won't make my app hold a wake lock 24/7
